// Code generated by goctl. DO NOT EDIT.
package types

import "time"

type UploadResp struct {
	Url string `json:"url"`
}

type RemoveReq struct {
	S3Authorization string `json:"s3Authorization,optional"`
	ObjectID        string `json:"objectID"`
	Path            string `json:"path"`
}

type DownloadReq struct {
	S3Authorization string `json:"s3Authorization,optional"`
	ObjectID        string `json:"objectID"`
	Path            string `json:"path"`
}

type DownloadResp struct {
	Url string `json:"url"`
}

type ObjectListReq struct {
	S3Authorization string `json:"s3Authorization,optional"`
	Prefix          string `json:"prefix,optional"` //Only list objects with the prefix
}

type ObjectInfo struct {
	Type         string            `json:"type"`
	ObjectID     string            `json:"objectID"`
	Path         string            `json:"path"`
	Size         int64             `json:"size"`
	ETag         string            `json:"eTag"`
	LastModified time.Time         `json:"lastModified"`
	Metadata     map[string]string `json:"metadata"`
}

type ObjectListResp struct {
	Items []ObjectInfo `json:"items"`
}

type RegisterReq struct {
	TenantID  string `json:"tenantID"`
	Namespace string `json:"namespace"` // 租户下二级分类，如：平台、子公司等
	UserID    string `json:"userID"`
}

type RegisterResp struct {
	AccessKey string `json:"accessKey"`
	SecretKey string `json:"secretKey"`
}

type TokenReq struct {
	AccessKey string `json:"accessKey"`
	SecretKey string `json:"secretKey"`
	Path      string `json:"path"`
}

type TokenResp struct {
	S3Authorization string `json:"S3Authorization"`
	ExpireIn        int64  `json:"expireIn"`
}
