// Code generated by goctl. DO NOT EDIT.
package types

type UploadResp struct {
	Url string `json:"url"`
}

type RemoveReq struct {
	S3Authorization string `json:"s3Authorization,optional"`
	Bucket          string `json:"bucket"`
	ObjectID        string `json:"objectID"`
	Path            string `json:"path"`
}

type DownloadReq struct {
	S3Authorization string `json:"s3Authorization,optional"`
	Bucket          string `json:"bucket"`
	ObjectID        string `json:"objectID"`
	Path            string `json:"path"`
}

type DownloadResp struct {
	Url string `json:"url"`
}

type ObjectListReq struct {
	Prefix     string `json:"prefix"`     //Only list objects with the prefix
	StartAfter string `json:"startAfter"` //start listing lexically at this object onwards
	Recursive  bool   `json:"recursive"`  //Ignore '/' delimiter
	MaxKeys    int    `json:"maxKeys"`    //The maximum number of objects
}

type ObjectListResp struct {
	ObjectName   string `json:"objectName"`
	Size         int64  `json:"size"`
	ETag         string `json:"eTag"`
	LastModified string `json:"lastModified"`
}

type RegisterReq struct {
	TenantID  string `json:"tenantID"`
	Namespace string `json:"namespace"` // 租户下二级分类，如：平台、子公司等
	UserID    string `json:"userID"`
}

type RegisterResp struct {
	AccessKey string `json:"accessKey"`
	SecretKey string `json:"secretKey"`
}

type TokenReq struct {
	AccessKey string `form:"accessKey"`
	SecretKey string `form:"secretKey"`
	Path      string `form:"path"`
}

type TokenResp struct {
	S3Authorization string `json:"S3Authorization"`
	ExpireIn        int64  `json:"expireIn"`
}
