// Code generated by goctl. DO NOT EDIT.
package types

type UploadResp struct {
	Url string `json:"url"`
}

type RemoveReq struct {
	S3Authorization string `json:"S3Authorization,optional"`
	ObjectID        string `json:"objectID"`
	Path            string `json:"path"`
}

type DownloadReq struct {
	S3Authorization string `json:"S3Authorization,optional"`
	Bucket          string `form:"bucket"`
	ObjectID        string `form:"objectID"`
	Path            string `form:"path"`
}

type RegisterReq struct {
	TenantID  string `json:"tenantID"`
	Namespace string `json:"namespace"` // 租户下二级分类，如：平台、子公司等
	UserID    string `json:"userID"`
}

type RegisterResp struct {
	AccessKey string `json:"accessKey"`
	SecretKey string `json:"secretKey"`
}

type TokenReq struct {
	AccessKey string `json:"accessKey"`
	SecretKey string `json:"secretKey"`
	Path      string `json:"path"`
}

type TokenResp struct {
	S3Authorization string `json:"S3Authorization"`
	ExpireIn        int64  `json:"expireIn"`
}
