// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"gitlab.energy-envision.com/storage/internal/svc"

	"github.com/tal-tech/go-zero/rest"
)

func RegisterHandlers(engine *rest.Server, serverCtx *svc.ServiceContext) {
	engine.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/object/upload",
				Handler: ObjectHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/object/remove",
				Handler: RemoveHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/object/download",
				Handler: DownloadHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/object/list",
				Handler: ObjectListHandler(serverCtx),
			},
		},
	)

	engine.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/user/registerUser",
				Handler: RegisterHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/askToken",
				Handler: TokenHandler(serverCtx),
			},
		},
	)
}
